### ISSUE TITLE
Single Sign-On (Keycloak) @ OCF

### ISSUE THREAD

**Issue by fydai** [ocf/projects#29]

**Comment by ethanhs** [comment]
What is there left for this?

**Comment by cg505** [comment]
Migrate remaining services

**Comment by dkess** [comment]
This could probably be split into a single issue for each service, but I can write a bit about what we can do here:

* Grafana has native OAuth support, but has no way of identifying what groups users are in. I'm tracking https://github.com/grafana/grafana/pull/17149-- once that gets merged, we should be able to migrate Grafana. I already wrote and tested most of the config for this.
* Kanboard is similar, though I don't know about its group support
* We could probably do this in a clever way with ocfweb (is there a Django library for this?)
* I don't think we should migrate Jenkins since it would add a dependency on Kubernetes
* Haven't investigated Metabase, Snipe-IT, Sourcegraph
* Puppetboard should be relatively to migrate, we can just use Keycloak Gatekeeper
* We could potentially do some clever configuration to authenticate Kubernetes users on Keycloak, though I haven't looked too much into this.

**Comment by nikhiljha** [comment]
more or less done, remaining issues tracked in their respective projects
